/**
 * SWC-based build script (replaces `nest build`/`tsc` — 0_Phase.md §1 trap 5).
 * Emits ESM to dist/ WITH decorator metadata, which tsx (esbuild) cannot do.
 * Usage: node scripts/build.mjs
 */
import swc from '@swc/core';
import { mkdir, readFile, readdir, writeFile, stat } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';

const { transform } = swc;

const SRC = 'src';
const OUT = 'dist';

/** Recursively collect source files (skip tests + generated by default). */
async function collect(dir, { includeTs = false, skipGenerated = true } = {}) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.isDirectory() && skipGenerated && entry.name === 'generated') continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collect(full, { includeTs, skipGenerated })));
    } else if (includeTs && (entry.name.endsWith('.ts') || entry.name.endsWith('.js') || entry.name.endsWith('.json'))) {
      if (!entry.name.endsWith('.test.ts') && !entry.name.endsWith('.d.ts')) files.push(full);
    } else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts') && !entry.name.endsWith('.d.ts')) {
      files.push(full);
    }
  }
  return files;
}

const files = await collect(SRC);
for (const file of files) {
  const source = await readFile(file, 'utf8');
  const out = await transform(source, {
    filename: file,
    sourceMaps: true,
    module: { type: 'es6', strictModule: true },
    jsc: {
      parser: { syntax: 'typescript', decorators: true, dynamicImport: true },
      transform: { legacyDecorator: true, decoratorMetadata: true },
      target: 'es2022',
    },
  });
  const rel = relative(SRC, file).replace(/\.ts$/, '.js');
  const dest = join(OUT, rel);
  await mkdir(dirname(dest), { recursive: true });
  await writeFile(dest, out.code);
  if (out.map) await writeFile(`${dest}.map`, JSON.stringify(out.map));
}

// Copy the generated Prisma client. Prisma 7's `prisma-client` generator
// emits TypeScript even with moduleFormat=esm — compile it through SWC too.
const generatedDir = join(SRC, 'generated');
try {
  await stat(generatedDir);
  const genFiles = await collect(generatedDir, { includeTs: true });
  for (const gf of genFiles) {
    const rel = relative(SRC, gf).replace(/\.ts$/, '.js');
    const dest = join(OUT, rel);
    await mkdir(dirname(dest), { recursive: true });
    if (gf.endsWith('.ts')) {
      const source = await readFile(gf, 'utf8');
      const out = await transform(source, {
        filename: gf,
        sourceMaps: false,
        module: { type: 'es6', strictModule: true },
        jsc: {
          parser: { syntax: 'typescript', decorators: true, dynamicImport: true },
          transform: { legacyDecorator: true, decoratorMetadata: true },
          target: 'es2022',
        },
      });
      await writeFile(dest, out.code);
    } else {
      await writeFile(dest, await readFile(gf));
    }
  }
  console.log(`generated prisma client compiled → ${OUT}/generated/`);
} catch {
  console.log('no generated dir; run `prisma generate` first');
}

console.log(`built ${files.length} modules → ${OUT}/`);
